import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import v from '../images/v.png'
import o from '../images/o.png'
import g from '../images/g.png'
import z from '../images/z.png'
import nikeN from '../images/nikeN.png'
import nikeB from '../images/nikeB.png'
import serrage from '../images/serrageMain.png'
import rect1 from '../images/Rectangle 51.png'
import rect2 from '../images/Rectangle 52.png'
import rond from '../images/rondNoir.png'
import pointR from '../images/pointR.png'
import rect3 from '../images/Rectangle 53.png'
import rect4 from '../images/Rectangle 54.png'
import polygone from '../images/Polygone.png'
import chaussure from '../images/chaussure.png'
import piece from '../images/piece.png'
import musique from '../images/musique.png'
import micro from '../images/micro.png'
import micro2 from '../images/micro2.png'






export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
  <div className="grid-element">
  <Image src={v} width="24.11" height="23.64"  />
  <Image src={o} width="24.38" height="24.22" />
  <Image src={g} width="23.55" height="24.08" />
  <Image src={z} width="16.8" height="23.64" />



  </div>

  <div id={styles.premier} >
  <Image id={styles.nikeN} src={nikeN} height= "86px" width= "229px" />
  &nbsp; &nbsp; &nbsp; &nbsp;   &nbsp; &nbsp; &nbsp; &nbsp;
  <Image src={serrage} width= "109px" height= "109px"/>
  &nbsp; &nbsp; &nbsp; &nbsp;   &nbsp; &nbsp; &nbsp; &nbsp;
  <Image className={styles.vogz} src={v} height= "56px" width= "57px" />
  <Image className={styles.vogz}  src={o} height= "57px" width= "57px" />
  <Image className={styles.vogz}  src={g} height= "57.px" width= "56px" />
  <Image className={styles.vogz}  src={z} height= "56px" width= "39px" />    
  </div>

<br></br>
  
  <div id={styles.deuxieme}>

   <div id={styles.troisieme}>

    <p id={styles.p}>
        “Marque” s’associe à VOGZ, pour vous permettre de participer à l’un de ses castings ! Le concept est simple : suivez les instructions du brief, filmez-vous, envoyez votre vidéo via notre application et si “Marque” sélectionne votre création vous êtes rémunéré !
    </p>

    <p id={styles.pp}>Collaborer avec vos marques préférés n’a jamais été aussi facile. C’est aussi simple que tourner un TikTok !
    </p>
    <button id={styles.button1} name="button">Participez au casting</button>


   </div>

    <div id={styles.quatrieme}>
    <Image id={styles.image1} src={rect1} />
    <Image id={styles.image2} src={rect2} />


   </div>

</div>

    <br></br> <br></br>

  <div id={styles.cinquieme}>

      <div id={styles.cinquieme1}>

        <Image className={styles.nikeB} src={nikeB} />
      </div>


      <div id={styles.cinquieme2}>

         <h1 id={styles.titre1}>Nike</h1>
         <p id={styles.p1}>Review Air Jordan 1 - University</p>
          
         <p id={styles.p2} >Test Produit</p>
         <p  id={styles.p3}>Casting plus</p>
        </div>

  </div>

      <p id={styles.p4}> 🔥 Derniers jours pour participer 🔥
</p>



<div id={styles.sixieme}>


    <hr className={styles.hr}></hr>


  <div id={styles.sixieme1}>

    <p  id={styles.p5}>Durée de la vidéo</p>
    <p  id={styles.p6}>Rémunération</p>
    <p  id={styles.p7}>Vogz coin</p>

   </div>

   <div id={styles.sixieme2}>

    <p  id={styles.p8}>30sec - 1min</p>
    <p  id={styles.p9}>250 </p>
    <p  id={styles.p10}>4</p>
    <Image  src={piece} />


    </div>

    <hr className={styles.hr}></hr>


 </div>



  <div id={styles.septieme}>

      <h1  id={styles.titre2}>Brief_</h1>

      <p id={styles.p11}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et sed arcu pretium nisl iaculis cras mauris amet amet. Eget posuere ac et lobortis est diam. Vestibulum quam convallis magna urna mattis. Faucibus neque, sit mauris amet diam. Arcu, cras rhoncus amet habitasse. Erat convallis nulla interdum aliquam neque, convallis auctor maecenas in. Sit ut ac quam diam tortor. Id porttitor risus vel vel diam. Volutpat porttitor tellus suspendisse odio molestie pellentesque. In in nisi massa, vitae pharetra a. Fringilla odio tortor dignissim feugiat. Egestas venenatis, cras auctor vitae volutpat scelerisque volutpat ornare ultricies. Suspendisse amet et nulla leo aliquet pellentesque elit. Eu commodo quis velit commodo. Sed purus lacinia nam ultrices morbi id vitae cras pellentesque. Purus.</p>


   </div>




   <div className={styles.huitieme}>

   <div className={styles.huitieme2}>


        <h1  className={styles.titre3}>Audio_</h1>

        <p className={styles.p12}>Ce casting nécéssite <font color="blue">obligatoirement </font>d’intégrer une piste audio. Le lien à télécharger se trouve ci-dessous</p>
        <button className={styles.button} name="button">LoremlpsumAudio.mp3</button>

        </div>

        <div className={styles.huitieme3}>

        <Image id={styles.musique} src={musique} />
    </div>

    </div>

                                                    <br></br>

      <div className={styles.huitieme}>

      <div className={styles.huitieme2}>

          <h1  className={styles.titre3}>Script_</h1>

          <p className={styles.p12}>Ce casting nécéssite <font color="blue">obligatoirement </font>d’intégrer une piste audio. Le lien à télécharger se trouve ci-dessous</p>
          <button className={styles.button} name="button">Nike_University.pdf</button>
        
        </div>

          <div className={styles.huitieme3}>

          <div id={styles.huitieme4}>
          <Image id={styles.micro2} src={micro2} />

          </div>
          
          <div id={styles.huitieme5}>
          <Image id={styles.micro} src={micro} />
          </div>
        </div>

      </div>


      <div id={styles.neuvieme}>

      <h1  id={styles.titre4}>Prérequis_</h1>

        <ul>

          <li className={styles.li}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>
          <li className={styles.li}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>
          <li className={styles.li}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>
          <li className={styles.li}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>
          <li className={styles.li}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>


        </ul>
          

      </div>

    

      <h1  id={styles.titre5}>Scénario_</h1>
      <div className={styles.dixieme}>

      <div className={styles.dixieme1}>

          <h1 className={styles.titre6}>1</h1>

      </div> 
      
      <div className={styles.dixieme2}>

        <p className={styles.p13}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus auctor laoreet ultrices sagittis, id phasellus eu. </p>
    
       </div>

      </div>

              <br></br>

                <div className={styles.dixieme}>

          <div className={styles.dixieme3}>

              <h1 className={styles.titre6}>2</h1>

          </div> 

          <div className={styles.dixieme2}>

            <p className={styles.p13}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus auctor laoreet ultrices sagittis, id phasellus eu. </p>

          </div>

          </div>


              <br></br>

            <div className={styles.dixieme}>

            <div className={styles.dixieme1}>

                <h1 className={styles.titre6}>3</h1>

            </div> 

            <div className={styles.dixieme2}>

              <p className={styles.p13}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus auctor laoreet ultrices sagittis, id phasellus eu. </p>

            </div>

            </div>

            <br></br>

              <div className={styles.dixieme}>

              <div className={styles.dixieme3}>

                  <h1 className={styles.titre6}>4</h1>

              </div> 

              <div className={styles.dixieme2}>

                <p className={styles.p13}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus auctor laoreet ultrices sagittis, id phasellus eu. </p>

              </div>

              </div>


              <div id={styles.onzieme}>

              <h1  id={styles.titre7}>Ratio de la vidéo_</h1>

                <div id={styles.onzieme1}>
                  <h2 id={styles.titre8}>REC</h2>
                  <Image  src={pointR} height= "12px" width= "12px" />

                </div>

                <div id={styles.onzieme2}>
               
               <p id={styles.p14}>Ce casting nécéssite d’être filmé au <font color="blue">FORMAT PAYSAGE </font></p>
                </div>

              </div>


                <br></br>
                          
             <div className={styles.huitieme}>

             <h1  id={styles.titre9}>Remarques_</h1>

              <ul>

            <li className={styles.li2}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>
            <li className={styles.li2}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>
            <li className={styles.li2}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis tincidunt.</li>


            </ul>

            </div>


            <div id={styles.douzieme}>

                <h1  id={styles.titre10}>Inspirations_</h1>

                <p id={styles.p15}>In in nisi massa, vitae pharetra a. Fringilla odio tortor dignissim feugiat. Egestas venenatis, cras auctor vitae volutpat scelerisque volutpat ornare ultricies. Suspendisse amet et nulla leo aliquet pellentesque elit. Eu commodo quis velit commodo. Sed purus lacinia nam ultrices morbi id vitae cras pellentesque. Purus.</p>


            </div>

            <br></br><br></br>

            <div id={styles.douzieme1}>


            <Image id={styles.image4}  src={polygone} width="150px" height="210px"/>

            <Image id={styles.image5} src={polygone} width="150px" height="210px"  />
            </div>


            <div id={styles.treizieme}>

              <h1  id={styles.titre11}>A voir aussi</h1>

              <p id={styles.p16}>In in nisi massa, vitae pharetra a. Fringilla odio tortor dignissim feugiat. Egestas venenatis, cras auctor vitae volutpat scelerisque volutpat ornare ultricies. Suspendisse amet et nulla leo aliquet pellentesque elit. Eu commodo quis velit commodo. Sed purus lacinia nam ultrices morbi id vitae cras pellentesque. Purus.</p>


            </div>

            <br></br>

            <div id={styles.quatorzieme}>

            <div id={styles.quatorzieme1}>

                  <Image className={styles.nikeB} src={nikeB} height= "43px" width= "89px" />

                  <br></br><br></br><br></br>
              <a href='https://www.nike.com/fr/' id={styles.p17}>Le site de Nike</a>
            </div>

              <div id={styles.quatorzieme2}>

              <Image className={styles.chaussure} src={chaussure} height= "130px" width= "130px" />
              <a href='https://www.tiktok.com/discover/sneakersaddict?lang=fr' id={styles.p18}>Le compte tiktok @Sneakersaddict</a>
              </div>

            </div>

            <br></br> <br></br>

            <div id={styles.quinzieme}>

              <h1  id={styles.titre12}>Notre histoire_</h1>

              <p id={styles.p19}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et sed arcu pretium nisl iaculis cras mauris amet amet. Eget posuere ac et lobortis est diam. Vestibulum quam convallis magna urna mattis. Faucibus neque, sit mauris amet diam. Arcu, cras rhoncus amet habitasse. Erat convallis nulla interdum aliquam neque, convallis auctor maecenas in. Sit ut ac quam diam tortor. Id porttitor risus vel vel diam. Volutpat porttitor tellus suspendisse odio molestie pellentesque. In in nisi massa, vitae pharetra a.</p>


            </div>

          <br></br>          <br></br>           <br></br>

            <button id={styles.button2} name="button">Participez au casting</button>



      </main>
        <br></br>
        <br></br><br></br>
      <footer className={styles.footer}>
   
   <div id={styles.divFooter1}>
      <p  id={styles.pFooter1}>Politique de confidentialité </p>
      <p  id={styles.pFooter2}>Mentions légales </p>

  </div>

      
      <div id={styles.divFooter2}>

      <p  id={styles.pFooter3}>Qui sommes-nous ? </p>
      <p  id={styles.pFooter4}>Espace marque</p>

      </div>

      <div id={styles.divFooter3}>


      <p  id={styles.pFooter5}>Contactez-nous ! </p>
      <p  id={styles.pFooter6}>01 84 88 47 96</p>

      </div>

      <div id={styles.divFooter4}>

      <Image
      src="/v.png"
      layout="fill"
      sizes="height: 50.84314727783203px;
      width: 51.84686279296875px;
      left: 1125px;
      top: 6066.703125px;
      border-radius: 0px;
      "
    />
       <Image
      src="/o.png"
      layout="fill"
      sizes="height: 52.081573486328125px;
      width: 52.43422317504883px;
      left: 1176.9912109375px;
      top: 6066px;
      border-radius: 0px;
      "
    />

<Image
      src="/g.png"
      layout="fill"
      sizes="height: 51.789981842041016px;
      width: 50.65531539916992px;
      left: 1233.83544921875px;
      top: 6066.126708984375px;
      border-radius: 0px;
      "
    />

<Image
      src="/z.png"
      layout="fill"
      sizes="height: 50.84314727783203px;
      width: 36.122955322265625px;
      left: 1288.87646484375px;
      top: 6066.703125px;
      border-radius: 0px;
      "
    />
      </div>
      </footer>
    </div>
  )
}
